name: lively_prem
services:
  stable-diffusion-webui:
    cpu_shares: 90
    command: []
    container_name: automatic1111-docker
    deploy:
      resources:
        limits:
          memory: 15771M
    hostname: automatic1111-docker
    image: ghcr.io/ai-joe-git/automatic1111-docker:main
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/StableDiffusionWebUI/icon.png
    ports:
      - target: 7860
        published: "7860"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/models
        target: /DATA/AppData/Stable-Diffusion-WebUI/models
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/vae
        target: /DATA/AppData/Stable-Diffusion-WebUI/vae
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/lora
        target: /DATA/AppData/Stable-Diffusion-WebUI/lora
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/embeddings
        target: /DATA/AppData/Stable-Diffusion-WebUI/embeddings
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/outputs
        target: /DATA/AppData/Stable-Diffusion-WebUI/outputs
      - type: bind
        source: /DATA/AppData/Stable-Diffusion-WebUI/config
        target: /DATA/AppData/Stable-Diffusion-WebUI/config
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/StableDiffusionWebUI/icon.png
  index: /
  is_uncontrolled: false
  port_map: "7860"
  scheme: http
  store_app_id: lively_prem
  title:
    custom: Stable Diffusion CPU
