services:
  automatic1111:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/joshbuker/automatic1111-docker:main
    volumes:
      - ~/Models:/model:ro
    tty: true
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # Testing multiple GenAI services using GPUs, seems to work fine
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
     - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama: {}
